---
title: "Research"
---

## Peer-Reviewed Articles

[3] **Heering, Jonas**, Loriana Crasnic, and Abraham Newman. (2025). "When Digital Taxes Come Due: National Digital Taxes and the Negotiation of the OECD Inclusive Framework." *New Political Economy*, 30(2), 178-193. [https://doi.org/10.1080/13563467.2024.2405524](https://doi.org/10.1080/13563467.2024.2405524)

::: {.callout-note collapse="true" appearance="minimal"}
## Abstract

What explains major shifts in international tax cooperation? Existing literature emphasises either the centrality of the United States for successful reform or the power of multinational corporations to exert downward pressure on global tax rates. Nonetheless, in 2021 members of the OECD Inclusive Framework (IF) agreed to tax some of the largest multinational companies based on their market activities rather than physical presence – a fundamental change to the international taxation regime that the U.S. government and U.S. multinational corporations (MNCs) had long opposed. We argue that the spread of digital value chains has exposed the activities of MNCs to greater regulatory activity, allowing governments to use unilateral regulatory action as leverage in international negotiations. By shifting the reversion point – the status quo absent an international agreement – governments were collectively able to transform an agreement. We demonstrate our argument by examining how the implementation of national digital services taxes (DSTs) affected the OECD IF negotiations. Drawing on interviews with key stakeholders and primary sources, we show that the adoption of DSTs, including in France and India, and the threat of additional proliferation of DSTs, pushed the United States to drop its longstanding opposition to parts of the IF process.
:::

[2] **Heering, Jonas**, Guillaume Beaumier, and Abraham Newman. (2024). "Running out the digital clock: Transatlantic privacy politics and veto points in time." *Journal of European Integration*, 46(7), 993-1013. [https://doi.org/10.1080/07036337.2024.2312098](https://doi.org/10.1080/07036337.2024.2312098)

::: {.callout-note collapse="true" appearance="minimal"}
## Abstract

Why does the European Commission continue to sign onto unstable international data flow agreements with the United States? After two agreements were struck down by the European Court of Justice, and clear signals that a new one could meet a similar fate, the European Commission agreed to the Data Privacy Framework. To make sense of this behavior, we connect traditional work on veto points with work on historical institutionalism to highlight an international negotiation strategy – running out the clock. While traditional veto points literature suggests multiple institutions with varying preferences will limit the set of potential policies or their adoption, we highlight how these dynamics change when considering veto points in time. We showcase our argument by building three historical narratives detailing the negotiation of the successive data flow agreements. Our findings have important implications for the future of the transatlantic privacy regime as well as negotiation dynamics.
:::

[1] **Heering, Jonas** and Thane Gustafson. (2021). "Germany's Energiewende at a Crossroads." *German Politics & Society*, 39(2). [https://doi.org/10.3167/gps.2021.390208](https://doi.org/10.3167/gps.2021.390208)

## Working Papers

**Heering, Jonas** and Erik Voeten. "The Data Center Dilemma: public preferences on the tradeoffs between the green and digital transition."

**Heering, Jonas** and Abraham Newman. "When Private Regulation Backfires: Mistrust in Firms Increases Support for Social Media Regulation."

**Heering, Jonas**, Guillaume Beaumier, and Abraham Newman. "A Digital Divide? Principles of Digital Market Governance in the EU and the US."

**Heering, Jonas**, Niccolò Bonifai, and Abraham Newman. "When Big Tech Helps Big Brother: How the Civil Liberty-Security Tradeoff Shapes Individuals' Attitudes Toward Technology Company Involvement in Government Surveillance."
